version: '3.9'
services:
  mysqldb:
    image: mysql
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      #MYSQL_USER: myuser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      #MYSQL_PASSWORD: pass4Nasir
    volumes:
      - ./my-data:/var/lib/mysql
      #- ./init-db/init.sql:/docker-entrypoint/init.sql:ro
    ports:
      - "3306:3306"
    command: 'mysqld --default-authentication-plugin=mysql_native_password'

  # PhpMyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8050:80"
    depends_on:
      - mysqldb
  #Central Warehouse VMS FE
  aescpsvms-fe:
    image: devopsaes/cpvms-fe:0.0.1
    container_name: aes-cpsvms-fe
    restart: always
    ports:
      - "5080:80"
    depends_on:
      - mysqldb
  #Central Warehouse VMS
  aescpsvms:
    build: .
    container_name: aes-cpsvms
    restart: always
    ports:
      - "9090:8082"
    depends_on:
      - mysqldb
volumes:
  mysql-data: