----INSERT INTO user_credential (id, email_address, password, active)
----VALUES (1,'superadmin@gmail.com','$2a$12$XMG3cM8IzAtwe3NsWn/HRuWmvUJ3YNzDMOCEysSoonoDihx6Dsysi', true);
----
----INSERT INTO users (id, email_address, first_name, last_name, user_credential_id)
----VALUES (1, "superadmin@gmail.com","john","doe",1);
----INSERT INTO user_credential (id, email_address, password, active)
----VALUES (2,'test@gmail.com','$2a$12$XMG3cM8IzAtwe3NsWn/HRuWmvUJ3YNzDMOCEysSoonoDihx6Dsysi', true);
----
----INSERT INTO users (id, email_address, first_name, last_name, user_credential_id)
----VALUES (2, "test@gmail.com","john","doe",1);
--
--insert into role(id, role_name) values (1, 'SYS_ADMIN');
--insert into role(id, role_name) values (2, 'USER');
--insert into role(id, role_name) values (3, 'EMPLOYEE');
--insert into role(id, role_name) values (4, 'VENDOR');
--insert into role(id, role_name) values (5, 'CUSTOMER');
--
--insert into user_credential_to_role(id, user_credential_id, role_id) values (1, 1, 1);
--
--insert into role_node (id, name, parent_id, parent_department_id)
--values (1, 'RootRoleNode', null, null);
--
--insert into department (id, has_user, name, parent_department_id, root_role_node_id, level)
--values (1, 0, 'root', null, 1, 0);
--
--
--insert into user_assignment (id,department_id,parent_user_assignment_id,role_node_id,user_id) values
--    (1,null,null,null,1);


--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (4, 'Organizations' ,'dashboard.svg','control-panel/organizations','control-panel/organizations', 'CHILD',null,1,1);
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (5, 'Inventory Control' ,'dashboard.svg','inventory-control','inventory-control', 'CHILD',3,1,1);
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (2, 'Registration' ,'dashboard.svg','vendor-panel/documents-verification','vendor-panel/documents-verification', 'CHILDREN',1,1,1);


--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (2, 'HR Module' ,'hrModule.svg',null,null, 'PARENT',null,2,1);
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (3, 'Employees' ,null,'employees','employees', 'CHILD',2,3,1);
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (4, 'Organogram' ,null,'organogram','organogram', 'CHILD',2,4,1);
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (5, 'Requisitions' ,null,'requisitions','requisitions', 'CHILD',2, 5,1);
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (6, 'Attendance' ,null,'attendance','attendance', 'CHILD',2, 6,1);
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (7, 'LRM' ,null,'lrm','lrm', 'CHILD',2, 7,1);
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (8, 'Pay Roll' ,null,'payrole','payrole', 'CHILD',2, 8,1);
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (9, 'Allowance' ,null,'allowance','allowance', 'CHILD',2, 9,1);
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (10, 'Overtime' ,null,'overtime','overtime', 'CHILD',2, 10,1);
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (11, 'Exit' ,null,'exit','exit', 'CHILD',2, 11,1);
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (12, 'SALES Module' ,'salesModule.svg',null,null, 'PARENT',null, 12,1);
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (13, 'SCM Module' ,'SCM.svg',null,null, 'PARENT',null,13,1);
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (14, 'Vendor Registration' ,null,'vendors','vendors', 'CHILD',13,14,1);
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (15, 'Create Demand' ,null,'create-demand','create-demand', 'CHILD', 13, 15,0);
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (16, 'My Demand' ,null,'demand/my-demand','demand/my-demand', 'CHILD',13,16,1);
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id,display_order, show_in_menu) VALUES
--                    (17, 'Pending Demand' ,null,'pending-demand','pending-demand', 'CHILD',13,17,0);
--
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id,display_order, show_in_menu) VALUES
--                    (32, 'Pending Verification' ,null,'pending-verification','pending-verification', 'CHILD',13,17,0);
--
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (18, 'Close Demand' ,null,'close-demand','close-demand', 'CHILD',13,18,0);
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (19, 'Indent Request' ,null,'indent-request','indent-request', 'CHILD',13,19,1);
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (20, 'Enlistment Request' ,null,'enlistment','enlistment', 'CHILD',13,20,1);
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (21, 'CS' ,null,'cs','cs', 'CHILD',13,21,1);
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (22, 'Inventory Module' ,'defaultModule.svg',null,null, 'PARENT',null,22,1);
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (23, 'Manage Category' ,null,'inventory-management/main-category','inventory-management/main-category', 'CHILD',22,23,1);
--
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (24, 'Manage Product' ,null,'inventory-management/product-management','inventory-management/product-management', 'CHILD',22,24,1);
--
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (25, 'Production Module' ,'defaultModule.svg',null,null, 'PARENT',null,25,1);
--
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (26, 'Logistic Module' ,'defaultModule.svg',null,null, 'PARENT',null,26,1);
--
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (27, 'Distribution Module' ,'defaultModule.svg',null,null, 'PARENT',null,27,1);
--
--INSERT INTO modules (id, name,icon,uri,route,module_type,parent_module_access_id, display_order, show_in_menu) VALUES
--                    (28, 'Accounts Module' ,'defaultModule.svg',null,null, 'PARENT',null,28,1);
                   
                   